<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CarFix.Application</RootNamespace>
  </PropertyGroup>

  
  <!--
    Application layer: Interfaces, DTOs, Services (business logic), Validators.
    References Domain only. Add FluentValidation / AutoMapper NuGet packages here
    as <PackageReference> items when you actually start implementing.
  -->

  <ItemGroup>
    <ProjectReference Include="..\CarFix.Domain\CarFix.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

</Project>
