<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>6b716f57-2273-4887-aa5b-0629495f76ce</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<!-- حزم الكيانات والأمان وقاعدة البيانات -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />

		<!-- حزمة OpenAPI الرسمية من Microsoft -->
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />

		<!-- واجهة Scalar للتصفح -->
		<PackageReference Include="Scalar.AspNetCore" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
		<!-- ربط الطبقات الأُخرى بالمشروع -->
		<ProjectReference Include="..\CarFix.Application\CarFix.Application.csproj" />
		<ProjectReference Include="..\CarFix.Domain\CarFix.Domain.csproj" />
		<ProjectReference Include="..\CarFix.Infrastructure\CarFix.Infrastructure.csproj" />
	</ItemGroup>

</Project>